Dodaj egzamin poprawkowy z 2022
wakacjezmd/wakacjezmd.github.io pull request #61
Opened 2022-09-08 12:37 UTC by Aleksander-Bloch

2022-09-08 13:47 UTC, aetn23 requested changes

2022-09-08 13:47 UTC, aetn23 commented on _solutions/2022/2022-egzamin-2.md
> +$$ 1 + x + x^2 +x^3 + x^4 + x^5 + x^6 + x^7 + x^8 \equiv 0 \quad (mod\ 133) $$
```suggestion
$$ 1 + x + x^2 +x^3 + x^4 + x^5 + x^6 + x^7 + x^8 \equiv 0 \pmod{133} $$
```

2022-09-08 13:47 UTC, aetn23 commented on _solutions/2018/2018-egzamin-2.md
> +<p>Niech \(b_n\) to liczba sposobów ustawienia n różnych książek na dwóch rozróżnialnych półkach (górnej i dolnej), tak że na każdej półce musi stać co najmniej jedna książka.</p>
```suggestion
<p>Niech \(b_n\) to liczba sposobów ustawienia \(n\) różnych książek na dwóch rozróżnialnych półkach (górnej i dolnej) tak, że na każdej półce musi stać co najmniej jedna książka.</p>
```

2022-09-08 13:47 UTC, aetn23 commented on _solutions/2018/2018-egzamin-2.md
> +Policz na ile sposobów można utworzyć kwadrat 3x3 składający się z poniższych płytek 1x1.
```suggestion
Policz na ile sposobów można utworzyć kwadrat \(3 \times 3\) składający się z poniższych płytek \(1 \times \).
```

2022-09-08 13:47 UTC, mikolaj-pirog commented on _solutions/2018/2018-egzamin-2.md
> +Udowodnij, że jeśli graf planarny ma mniej niż 30 krawędzi, to zawiera wierzchołek stopnia co najwyżej 4.
```suggestion
Udowodnij, że jeśli graf planarny ma mniej niż \(30\) krawędzi, to zawiera wierzchołek stopnia co najwyżej \(4\).
```

2022-09-08 13:48 UTC, aetn23 commented
Dzięki, rozumiem, że egzamin 2018 przepisywałeś ze słuchu z konsów?

2022-09-08 13:56 UTC, Aleksander-Bloch commented
> 

Tak

2022-09-08 14:00 UTC, Aleksander-Bloch commented
Wszystkie zadania z egzaminu poprawkowego z 2018 spisałem z nagrania konsultacji z Malinowskim.

2022-09-08 14:01 UTC, aetn23 commented
Super, podwójne dzięki, ze słuchu musiało być ciężko

2022-09-08 14:01 UTC, merged

2022-10-11 08:31 UTC, Aleksander-Bloch commented
Tak.

czw., 8 wrz 2022 o 15:49 Alek Bloch ***@***.***> napisał(a):

> Tak XD.
>
> czw., 8 wrz 2022 o 15:48 Mikołaj Piróg ***@***.***>
> napisał(a):
>
>> Dzięki, rozumiem, że egzamin 2018 przepisywałeś ze słuchu z konsów?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/wakacjezmd/wakacjezmd.github.io/pull/61#issuecomment-1240743623>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AKHSJ4FBCZDVJBGLKOZZZZDV5HVCVANCNFSM6AAAAAAQHWOBUU>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>